forge 'https://forgeapi.puppetlabs.com'
mod 'it2ndq/barman', :git => 'git://github.com/2ndquadrant-it/puppet-barman.git'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/puppetdb'
mod 'stephenrjohnson/puppet'
